"""[MODIFY] : Time stamp 적용

Revision ID: 7d60008dc586
Revises: 5d829d0ed4b6
Create Date: 2023-03-13 10:41:18.558120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d60008dc586'
down_revision = '5d829d0ed4b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postflavors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('postflavors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('useranswers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('useranswers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('userstacks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('userstacks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userstacks', 'updated_at')
    op.drop_column('userstacks', 'created_at')
    op.drop_column('useranswers', 'updated_at')
    op.drop_column('useranswers', 'created_at')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('postflavors', 'updated_at')
    op.drop_column('postflavors', 'created_at')
    # ### end Alembic commands ###
