name: Docker Build & Deploy
run-name: Github Action is running

# main branch에 push 또는 pull request 시에만 작동
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-depoly:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Requirements
        run: pip install -r backend/requirements.txt

      - name: Create my_settings.py
        run: |
          echo $(pwd)
          echo "SECRET_KEY='${{ secrets.MY_SECRET_KEY }}'" >> backend/my_settings.py
          echo "DATABASES='&{{ secrets.DATABASES }}'" >> backend/my_settings.py
          echo "SECRET_KEY='&{{ secrets.SECRET_KEY }}'" >> backend/my_settings.py
          echo "ALGORITHM='&{{ secrets.ALGORITHM }}'" >> backend/my_settings.py
          
          echo "GOOGLE_OAUTH2_REDIRECT_URI='&{{ secrets.GOOGLE_OAUTH2_REDIRECT_URI }}'" >> backend/my_settings.py
          echo "GOOGLE_OAUTH2_CLIENT_ID='&{{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}'" >> backend/my_settings.py
          
          echo "GOOGLE_MAIL_ADDRESS='&{{ secrets.GOOGLE_MAIL_ADDRESS }}'" >> backend/my_settings.py
          echo "GOOGLE_MAIL_APP_PWD='&{{ secrets.GOOGLE_MAIL_APP_PWD }}'" >> backend/my_settings.py

      - name: Run Django Test
        run: |
          if python backend/manage.py test backend/apps; then
            echo "::set-output name=test_result::OK"
          else
            echo "::set-output name=test_result::FAILED"
            exit 1
          fi
        
      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      
      # backend docker file 작성
      - name: Build Backend Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME}}/backend:latest
          
      # frontend docker file 작성
      - name: Build Frontend Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME}}/frontend:latest
            
      # ssh로 wesald EC2 접속.
      - name: Into Wesalad EC2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PEM_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME}}
      
      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      
      # 최신 docker image 가져오기
      - name: Pull Docker Image
        run: |
          docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker-compose down
          docker-compose up -d --force-recreate
