name: Docker Build & Depoly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-depoly:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # - name: Login DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME}}
      #     password: ${{ secrets.DOCKER_PASSWORD}}
        
      # - name: Build Backend Docker images # backend docker file 작성
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./backend
      #     push: true
      #     tags: |
      #       docker.io/${{ secrets.DOCKER_USERNAME}}/backend:latest
          
      # - name: Build Frontend Docker images # frontend docker file 작성
      #   uses: docker/build-push-action@v2
      #   with:
      #     context:  ./frontend
      #     push: true
      #     tags: |
      #       docker.io/${{ secrets.DOCKER_USERNAME}}/frontend:latest
            
        
      # - name: Into Wesalad EC2 # ssh로 wesald EC2 접속.
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     password: ${{ secrets.EC2_PASSWORD }}
      #     key: ${{ secrets.EC2_PRIBATE_KEY }}
      #     port: ${{ secrets.EC2_SSH_PORT }}
          
      #     # 최신 docker image 가져오기
      #     run: |
      #       docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/backend:latest
      #       docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/frontend:latest
      #       docker-compose down
      #       docker-compose up -d --force-recreate

      - name: TEST
        run: |
          echo "${{ secrets.EC2_PEM_KEY_2 }}" >> $HOME/wesalad.pem
          chmod 400 $HOME/wesalad.pem
          ssh -i $HOME/wesalad.pem -o StrictHostKeyChecking=no ${EC2_USERNAME}@${EC2_HOST}
          touch test.txt